import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import { SplatManager } from './SplatManager.js'

const MODEL_URL = '/gs_Parte_de_atr_s_pasillo_pi.compressed.ply'
const COLLISION_URL = '/gs_Parte_de_atr_s_pasillo_pi.collision.glb'
const MAX_SPLAT_BYTES = 200 * 1024 * 1024

const canvas = document.getElementById('xr-canvas')
const loadingEl = document.getElementById('loading')
const enterVrButton = document.getElementById('enter-vr')

const scene = new THREE.Scene()
scene.background = new THREE.Color(0x0a0a0c)

// --- ESCENARIO Y GROUND PLANE ---
const groundGeometry = new THREE.CircleGeometry(50, 64)
const groundMaterial = new THREE.MeshStandardMaterial({ color: 0x1a1a1a, roughness: 0.8, metalness: 0.2 })
const ground = new THREE.Mesh(groundGeometry, groundMaterial)
ground.rotation.x = -Math.PI / 2
scene.add(ground)

const grid = new THREE.GridHelper(50, 50, 0x2a2a2a, 0x111111)
scene.add(grid)

// Luces base para iluminar el suelo
const ambientLight = new THREE.AmbientLight(0xffffff, 0.5)
scene.add(ambientLight)
const dirLight = new THREE.DirectionalLight(0xffffff, 1)
dirLight.position.set(5, 10, 5)
scene.add(dirLight)

// --- JERARQUÍA DE CÁMARA (XR RIG) ---
const cameraGroup = new THREE.Group()
scene.add(cameraGroup)

const camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 0.01, 500)
// Altura promedio de un humano en Desktop (en XR local-floor domina el tracking de las Quest)
camera.position.set(0, 1.6, 3) 
camera.lookAt(0, 1.6, 0)
camera.layers.enable(0)
cameraGroup.add(camera)

const renderer = new THREE.WebGLRenderer({
  canvas,
  antialias: false,
  alpha: true,
  powerPreference: 'high-performance',
  precision: 'mediump'
})
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.5))
renderer.setSize(window.innerWidth, window.innerHeight, false)
renderer.xr.enabled = true
renderer.xr.setReferenceSpaceType('local-floor')
renderer.autoClear = true

const controls = new OrbitControls(camera, renderer.domElement)
controls.target.set(0, 1.6, 0)
controls.enableDamping = true
controls.rotateSpeed = 0.6
controls.zoomSpeed = 0.7

// Collision uses an invisible proxy mesh generated by splat-transform.
const COLLISION_LAYER = 1
const PLAYER_RADIUS = 0.25
const PLAYER_HEIGHT = 1.6
const collisionRaycaster = new THREE.Raycaster()
collisionRaycaster.layers.set(COLLISION_LAYER)
const collisionState = {
  root: null,
  ready: false
}
const collisionOrigin = new THREE.Vector3()
const collisionDirection = new THREE.Vector3()
const gltfLoader = new GLTFLoader()

const desktopMoveState = {
  forward: false,
  back: false,
  left: false,
  right: false
}
const desktopMoveSpeed = 0.06

const splatManager = new SplatManager({
  scene,
  renderer,
  camera,
  maxBytes: MAX_SPLAT_BYTES,
  allowPly: true,
  renderOrder: 2,
  disableDepthTest: true
})

function setLoading(isLoading, text = 'Loading splat...') {
  loadingEl.textContent = text
  loadingEl.classList.toggle('hidden', !isLoading)
}

function loadCollisionMesh() {
  return new Promise((resolve) => {
    gltfLoader.load(
      COLLISION_URL,
      (gltf) => {
        const root = gltf.scene
        let meshCount = 0
        root.traverse((child) => {
          child.layers.set(COLLISION_LAYER)
          if (child.isMesh) {
            meshCount += 1
            if (Array.isArray(child.material)) {
              child.material = child.material.map((material) => {
                const clone = material?.clone?.()
                const target = clone ?? material
                if (target) {
                  target.visible = false
                  target.side = THREE.DoubleSide
                }
                return target
              })
            } else if (child.material?.clone) {
              child.material = child.material.clone()
              child.material.visible = false
              child.material.side = THREE.DoubleSide
            } else if (child.material) {
              child.material.visible = false
              child.material.side = THREE.DoubleSide
            }
            child.castShadow = false
            child.receiveShadow = false
          }
        })
        root.layers.set(COLLISION_LAYER)
        scene.add(root)
        collisionState.root = root
        collisionState.ready = true
        console.log(`[Collision] Collider cargado con ${meshCount} meshes`)
        resolve(root)
      },
      undefined,
      (error) => {
        console.warn('[Collision] No se pudo cargar el collider:', error)
        collisionState.root = null
        collisionState.ready = false
        resolve(null)
      }
    )
  })
}

function alignCollisionToSplat() {
  const viewer = splatManager.getViewer()
  const splatMesh = viewer?.splatMesh
  if (!collisionState.root || !splatMesh) return

  splatMesh.updateMatrixWorld(true)
  splatMesh.matrixWorld.decompose(
    collisionState.root.position,
    collisionState.root.quaternion,
    collisionState.root.scale
  )
  collisionState.root.updateMatrixWorld(true)
}

function applyCollisionToVelocity(desiredVelocity) {
  if (!collisionState.ready || !collisionState.root) {
    return desiredVelocity
  }

  collisionDirection.set(desiredVelocity.x, 0, desiredVelocity.z)
  const distance = collisionDirection.length()
  if (distance === 0) return desiredVelocity

  collisionDirection.normalize()
  collisionOrigin.set(
    cameraGroup.position.x,
    cameraGroup.position.y + PLAYER_HEIGHT * 0.5,
    cameraGroup.position.z
  )

  collisionRaycaster.set(collisionOrigin, collisionDirection)
  collisionRaycaster.far = distance + PLAYER_RADIUS

  const hits = collisionRaycaster.intersectObject(collisionState.root, true)
  if (hits.length && hits[0].distance <= distance + PLAYER_RADIUS) {
    desiredVelocity.x = 0
    desiredVelocity.z = 0
  }

  return desiredVelocity
}

async function loadInitialSplat() {
  setLoading(true)
  try {
    // Calcular la rotación usando Euler para facilitar el ajuste.
    // Ej: -90 en X la levanta (si estaba acostada), 180 en Y la gira hacia ti.
    //const euler = new THREE.Euler(
    //  THREE.MathUtils.degToRad(-10), // Rotación X
    //  THREE.MathUtils.degToRad(185), // Rotación Y
    //  THREE.MathUtils.degToRad(179),   // Rotación Z
    //  'XYZ'
    //);
    const euler = new THREE.Euler(
      THREE.MathUtils.degToRad(10), // Rotación X
      THREE.MathUtils.degToRad(50), // Rotación Y
      THREE.MathUtils.degToRad(180),   // Rotación Z
      'XYZ'
    );
    const quat = new THREE.Quaternion().setFromEuler(euler);

    await splatManager.load(MODEL_URL, {
      onProgress: (progress) => {
        if (typeof progress === 'number') {
          const percent = Math.round(progress * 100)
          setLoading(true, `Loading splat... ${percent}%`)
        }
      },
      transform: {
        position: [0, 0, -3], // Posicionado a 3 metros al frente de la cámara
        rotation: [quat.x, quat.y, quat.z, quat.w], 
        scale: [1, 1, 1]
      }
    })
    if (!collisionState.ready) {
      await loadCollisionMesh()
    }
    alignCollisionToSplat()
    controls.update()
    setLoading(false)
  } catch (error) {
    console.error(error)
    setLoading(true, error.message || 'Failed to load splat')
  }
}

function updateRendererSize() {
  camera.aspect = window.innerWidth / window.innerHeight
  camera.updateProjectionMatrix()
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 1.5))
  renderer.setSize(window.innerWidth, window.innerHeight, false)
}

async function enterVR() {
  if (!navigator.xr) {
    alert('WebXR not available in this browser')
    return
  }

  enterVrButton.disabled = true

  try {
    const session = await navigator.xr.requestSession('immersive-vr', {
      optionalFeatures: ['local-floor']
    })
    renderer.xr.setSession(session)

    session.addEventListener('end', () => {
      enterVrButton.disabled = false
    })
  } catch (error) {
    console.error(error)
    enterVrButton.disabled = false
  }
}

enterVrButton.addEventListener('click', enterVR)
window.addEventListener('resize', updateRendererSize)
window.addEventListener('keydown', (event) => {
  switch (event.code) {
    case 'KeyW':
    case 'ArrowUp':
      desktopMoveState.forward = true
      break
    case 'KeyS':
    case 'ArrowDown':
      desktopMoveState.back = true
      break
    case 'KeyA':
    case 'ArrowLeft':
      desktopMoveState.left = true
      break
    case 'KeyD':
    case 'ArrowRight':
      desktopMoveState.right = true
      break
    default:
      break
  }
})
window.addEventListener('keyup', (event) => {
  switch (event.code) {
    case 'KeyW':
    case 'ArrowUp':
      desktopMoveState.forward = false
      break
    case 'KeyS':
    case 'ArrowDown':
      desktopMoveState.back = false
      break
    case 'KeyA':
    case 'ArrowLeft':
      desktopMoveState.left = false
      break
    case 'KeyD':
    case 'ArrowRight':
      desktopMoveState.right = false
      break
    default:
      break
  }
})
window.addEventListener('pagehide', () => {
  splatManager.dispose()
})

// --- SISTEMA DE LOCOMOCIÓN WEBXR ---
const moveSpeed = 0.05
const velocity = new THREE.Vector3()

// Guardar los tiempos para controlar el Snap Turn
const frameLog = { lastSnap: 0 }

function handleDesktopInputs(activeCamera) {
  let xAxis = 0
  let zAxis = 0
  if (desktopMoveState.forward) zAxis += 1
  if (desktopMoveState.back) zAxis -= 1
  if (desktopMoveState.right) xAxis += 1
  if (desktopMoveState.left) xAxis -= 1

  if (xAxis === 0 && zAxis === 0) return

  const forward = new THREE.Vector3(0, 0, -1)
  forward.applyQuaternion(activeCamera.quaternion)
  cameraGroup.localToWorld(forward)
  forward.sub(cameraGroup.position)
  forward.y = 0
  forward.normalize()

  const right = new THREE.Vector3().crossVectors(forward, new THREE.Vector3(0, 1, 0)).normalize()

  velocity.copy(forward).multiplyScalar(zAxis * desktopMoveSpeed)
  velocity.add(right.multiplyScalar(xAxis * desktopMoveSpeed))
  applyCollisionToVelocity(velocity)

  cameraGroup.position.add(velocity)
  controls.target.add(velocity)
}

function handleXRInputs(activeCamera) {
  const session = renderer.xr.getSession()
  if (!session || !session.inputSources) return

  for (const source of session.inputSources) {
    if (!source.gamepad) continue

    const gamepad = source.gamepad
    
    // Ejes de Quest 2/3/Pro (generalmente 2 y 3) con fallback a 0 y 1
    let xAxis = gamepad.axes.length > 2 ? gamepad.axes[2] : gamepad.axes[0] || 0
    let yAxis = gamepad.axes.length > 3 ? gamepad.axes[3] : gamepad.axes[1] || 0

    // Deadzone de 0.2 para evitar drift
    if (Math.abs(xAxis) < 0.2) xAxis = 0
    if (Math.abs(yAxis) < 0.2) yAxis = 0

    if (xAxis === 0 && yAxis === 0) continue

    if (source.handedness === 'left') {
      // 1. Obtener el vector "Adelante" (-Z) de la cámara en su espacio local
      const forward = new THREE.Vector3(0, 0, -1)
      forward.applyQuaternion(activeCamera.quaternion)
      
      // 2. Proyectar al mundo usando la matriz del grupo (rig)
      cameraGroup.localToWorld(forward)
      forward.sub(cameraGroup.position) // Obtener el vector direccional puro
      
      // 3. Restringir movimiento al plano horizontal (suelo)
      forward.y = 0 
      forward.normalize()

      // 4. Calcular el vector lateral derecho
      const right = new THREE.Vector3().crossVectors(forward, new THREE.Vector3(0, 1, 0)).normalize()

      // 5. Aplicar velocidad (en Quest, -yAxis es empujar el stick hacia adelante)
      velocity.copy(forward).multiplyScalar(-yAxis * moveSpeed)
      velocity.add(right.multiplyScalar(xAxis * moveSpeed))

      // Aplicar movimiento al Rig contenedor con colision basica
      applyCollisionToVelocity(velocity)
      cameraGroup.position.add(velocity)
      
    } else if (source.handedness === 'right') {
      // Snap Turn (Rotación por pasos para evitar mareo)
      const now = performance.now()
      if (now - frameLog.lastSnap > 300) { // Cooldown de 300ms
        if (xAxis > 0.5) {
          cameraGroup.rotation.y -= Math.PI / 4 
          frameLog.lastSnap = now
        } else if (xAxis < -0.5) {
          cameraGroup.rotation.y += Math.PI / 4 
          frameLog.lastSnap = now
        }
      }
    }
  }
  
  // CRÍTICO: Forzar la actualización de la matriz del grupo para que WebXR refleje el cambio
  cameraGroup.updateMatrixWorld(true)
}
// --- CICLO PRINCIPAL DE RENDERIZADO ---
renderer.setAnimationLoop(() => {
  const xrCamera = renderer.xr.isPresenting ? renderer.xr.getCamera(camera) : camera
  const activeCamera = xrCamera.isArrayCamera ? xrCamera.cameras[0] : xrCamera

  if (renderer.xr.isPresenting) {
    handleXRInputs(activeCamera)
  } else {
    handleDesktopInputs(activeCamera)
    controls.update()
  }

  const viewer = splatManager.getViewer()
  if (viewer) {
    viewer.update()
  }

  // 4. Renderizar escena completa (Three.js dibujará el splatMesh automáticamente)
  renderer.render(scene, camera)
})

loadInitialSplat()